# Generated by Django 6.0.3 on 2026-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500, verbose_name='Оригинальная ссылка')),
                ('short_url', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Короткая ссылка')),
                ('clicks', models.IntegerField(default=0, verbose_name='Количество переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
